# -*- coding: utf-8 -*-
"""3D ploting

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13wv8vGYeUvL17uW-OBQpOoabTrG9lsPs
"""

pip install matplotlib

pip install numpy

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d


fig = plt.figure(figsize = (12,10))
ax = plt.axes(projection='3d')

x = np.arange(-5, 5.1, 0.2)
y = np.arange(-5, 5.1, 0.2)

X, Y = np.meshgrid(x, y)
Z = np.sin(X)*np.cos(Y)

surf = ax.plot_surface(X, Y, Z, cmap = plt.cm.cividis)

# Set axes label
ax.set_xlabel('x', labelpad=20)
ax.set_ylabel('y', labelpad=20)
ax.set_zlabel('z', labelpad=20)

fig.colorbar(surf, shrink=0.5, aspect=8)

plt.show()

fig = plt.figure(figsize = (12,10))